/// -------------------------------------------------------
// ~This version is mainly generated by chagGPT 3.5
/// -------------------------------------------------------

"use strict";

const board = document.querySelector(".board");
const eraserButton = document.querySelector(".eraser");
let gridSize = 64;
let isMouseDown = false;

board.style.setProperty("--grid-size", gridSize);

board.addEventListener("mousedown", () => {
  isMouseDown = true;
});

board.addEventListener("mouseup", () => {
  isMouseDown = false;
});

for (let i = 0; i < gridSize * gridSize; i++) {
  const square = document.createElement("div");
  square.className = "square";
  square.addEventListener("mouseover", () => {
    if (isMouseDown) {
      square.style.backgroundColor = "black";
    }
  });
  board.appendChild(square);
}
